// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDX0V1GgmTxw8d_IJfqzBKXSuOo77EFHGw',
    appId: '1:829165622063:web:a227c92d3c8fdad618c7da',
    messagingSenderId: '829165622063',
    projectId: 'ticketpass-bf30a',
    authDomain: 'ticketpass-bf30a.firebaseapp.com',
    storageBucket: 'ticketpass-bf30a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVrUnxse7UFS7Sb6wWmUKzkQOl-SCVHZU',
    appId: '1:829165622063:android:06533633bd30028e18c7da',
    messagingSenderId: '829165622063',
    projectId: 'ticketpass-bf30a',
    storageBucket: 'ticketpass-bf30a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbnrhXQ4TGa15KtuGlgmA-OaSUAOXxJqM',
    appId: '1:829165622063:ios:0c7f7e6d41d1828718c7da',
    messagingSenderId: '829165622063',
    projectId: 'ticketpass-bf30a',
    storageBucket: 'ticketpass-bf30a.firebasestorage.app',
    iosClientId: '829165622063-ffeotjubfpgfpb2o54h51r1sd1v7604o.apps.googleusercontent.com',
    iosBundleId: 'com.example.ticketpass',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbnrhXQ4TGa15KtuGlgmA-OaSUAOXxJqM',
    appId: '1:829165622063:ios:0c7f7e6d41d1828718c7da',
    messagingSenderId: '829165622063',
    projectId: 'ticketpass-bf30a',
    storageBucket: 'ticketpass-bf30a.firebasestorage.app',
    iosClientId: '829165622063-ffeotjubfpgfpb2o54h51r1sd1v7604o.apps.googleusercontent.com',
    iosBundleId: 'com.example.ticketpass',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDX0V1GgmTxw8d_IJfqzBKXSuOo77EFHGw',
    appId: '1:829165622063:web:43a310078a99281218c7da',
    messagingSenderId: '829165622063',
    projectId: 'ticketpass-bf30a',
    authDomain: 'ticketpass-bf30a.firebaseapp.com',
    storageBucket: 'ticketpass-bf30a.firebasestorage.app',
  );
}
